# Required metadata
sonar.projectKey=syllabus_cliente
sonar.projectName=syllabus_cliente
sonar.projectVersion=1.0

sonar.sources=./
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.scss
#sonar.tests=src
#sonar.test.inclusions=**/*.spec.ts

sonar.sourceEncoding=UTF-8
